<div class="textContent">
    <div  style="text-align: center"><h1>Bestandsaufnahme</h1></div>
    <br />
    <p>Es existieren bereits einige Energiedatenportale, die sich mit den ver&ouml;ffentlichten Anlagenstammdaten der Netzbetreiber besch&auml;ftigen.</p>
    <br />
    <div class="websitePreviewDiv">
        <b>EnergyMap</b>
        <a href="http://www.energymap.info">
            <img class="websitePreview" src="img/EnergyMap.jpg">
        </a>
        <p>
            Die EnergyMap der Deutschen Gesellschaft f&uuml;r Sonnenenergie e.V. ver&ouml;ffentlicht aktuelle Daten zur Energiewende in Deutschland. Dabei werden die Anlagenstammdaten der Netzbetreiber zusammengetragen, in Grafiken veranschaulicht und stehen als CSV-Tabellen zum Download bereit. Es werden regionsspezifische Entwicklungen herausgestellt und durch kritische Bemerkungen zum EEG und den Netzbetreibern erg&auml;nzt.   
        </p>
        <div class="clear"></div>
    </div>
    <div class="websitePreviewDiv">
        <b>Solaratlas Leipzig</b>
        <a href="http://www.solaratlas.htwk-leipzig.de">
            <img class="websitePreview" src="img/Solaratlas.jpg">
        </a>
        <p>
            Der Solaratlas der HTWK Leipzig visualisiert dezentrale Energieerzeugungsanlagen in der Region Leipzig anhand einer Karte und erg&auml;nzt diese durch hervorgehobene Einzelbeispiele mit Erl&auml;uterungen und Bildern. Elektrotankstellen wurden ebenfalls in die Karte aufgenommen. Dar&uuml;ber hinaus bietet die Website weitere Informationen &uuml;ber die Energiepolitik in Deutschland und speziell in Leipzig. Au&szlig;erdem gibt sie einen &Uuml;berblick &uuml;ber alternative Energietr&auml;ger.
        </p>
        <div class="clear"></div>
    </div>
    <div class="websitePreviewDiv">
        <b>Solardach-Katastar Leipzig</b>
        <a href="http://www.solardachkataster.leipzig.de">
            <img class="websitePreview" src="img/Solardach-Katastar.jpg">
        </a>
        <p>
            Mit dem Solardachkataster der Stadt Leipzig liegt f&uuml;r das Gebiet der Stadt Leipzig eine fl&auml;chendeckende Standortanalyse und einzelfl&auml;chenbezogene Prognose des Potenzials der solaren Energieerzeugung auf geeigneten Dachfl&auml;chen vor. Die Karte bietet zu jedem Dach Informationen &uuml;ber Sonneneinstrahlung, m&ouml;glichem Ertrag und Eignung f&uuml;r Photovoltaik- und Solarthermieanlagen. Es handelt hier um eine Informationskarte mit beratendem Charakter zur Mobilisierung von Investitionen in Solaranlagen.
        </p>
        <div class="clear"></div>
    </div>
    <div class="websitePreviewDiv">
        <p>
            <b>Fazit</b><br />
            Anhand der aufgef&uuml;hrten Beispiele wird ersichtlich, dass bereits ein Informationsangebot zur Umsetzung der Energiewende in Deutschland und auch spezifisch f&uuml;r die Region Leipzig existiert. Dabei verfolgen unterschiedliche Portale und deren Betreiber unterschiedliche Ziele.
            Die e-Map Leipzig setzt ihren Schwerpunkt zum einen auf die Visualisierung der dezentralen Energieerzeugungsanlagen durch eine Verkn&uuml;pfung mit Geo-Daten. Zum anderen steht die offene Verkn&uuml;pfung der Daten auf Grundlage des Semantic Web besonders im Vordergrund.
        </p>
    </div>
</div>
<div class="clear"></div>