<div id="mapFrame">
    <div id="map"></div>
</div>
<div class="clear"></div>
<div id="filter">
    <div id="headLine">Filter</div>
    <div id="firstFilter">
        <div id="inbetriebnahmedatum">
            <div>
                <label for="from">Von</label>
                <input type="text" id="from" name="from">
            </div>
            <div>
                <label for="to">bis</label>
                <input type="text" id="to" name="to">
            </div>
        </div>
        <div id="enr">
            <label for="from">ENR</label>
            <input type="text" name="enrInput">
        </div>
        <div id="leistung">
            <label for="from">Leistung</label>
            <input type="text" id="amount" style="border:0; color:#f6931f; font-weight:bold;">
            <div id="slider-range"></div>
        </div>
        <div class="clear"></div>
    </div>
    <div id="secondFilter">
        <div id="energietraeger">
            <ol id="selectable"></ol>
        </div>
        <div id="einspeisungsebene">
            <ol id="selectable"></ol>
        </div>
        <div id="netzbetreiber">
            <ol id="selectable"></ol>
        </div>
        <div class="clear"></div>
        <div id="plz">
            <ol id="selectable"></ol>
        </div>
        <div class="clear"></div>
    </div>
    <div class="clear"></div>
</div>