<div class="textContent">
  <div style="text-align: center; margin-bottom: 30pt;">
    <h1>Impressum</h1>
  </div>

  Initiator: Prof. Dr. Hans-Gert Gr&auml;be<br /> Universit&auml;t
  Leipzig<br /> Fakult&auml;t f&uuml;r Mathematik und Informatik<br />
  Institut f&uuml;r Informatik<br /> PF 100920<br /> 04009 Leipzig<br />
  
  <br />Die Universit&auml;t Leipzig ist eine K&ouml;rperschaft des
  &Ouml;ffentlichen Rechts. Sie wird durch die Rektorin Prof. Dr. med. Beate
  A. Sch&uuml;cking gesetzlich vertreten.<br />

  <br /> Zust&auml;ndige Aufsichtsbeh&ouml;rde<br /> S&auml;chsisches
  Staatsministerium f&uuml;r Wissenschaft und Kunst<br /> Wigardstra&szlig;e
  17<br /> 01097 Dresden<br /> www.smwk.de<br />

  <br />Umsatzsteuer-Identifikationsnummer gem&auml;&szlig; &sect; 27 a
  Umsatzsteuergesetz<br /> DE 141510383<br />


    <br /> Die &bdquo;Erneuerbare Energien Karte&ldquo; wurde von einer
    interdisziplin&auml;ren Studentengruppe der Universit&auml;t Leipzig im
    Rahmen eines Praktikums erstellt.<br />

    <br /> Beratung und Betreuung durch Prof. Dr. Hans-Gert Gr&auml;be<br />

    <br /> <strong>Webdesign:</strong> Phillip Holl&auml;nder<br />

    <br />
    <strong>Disclaimer:</strong> Unser Angebot enth&auml;lt Links zu externen Webseiten
    Dritter, auf deren Inhalte wir keinen Einfluss haben. F&uuml;r die Inhalte
    der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der
    Seiten verantwortlich. F&uuml;r die Inhalte und die Richtigkeit der
    Informationen verlinkter Websites fremder Informationsanbieter wird keine
    Gew&auml;hr &uuml;bernommen.<br />

    <br /> Die durch die Seitenbetreiber erstellten Inhalte und Werke auf
    diesen Seiten unterliegen dem deutschen Urheberrecht. Die
    Vervielf&auml;ltigung, Bearbeitung, Verbreitung und jede Art der
    Verwertung au&szlig;erhalb der Grenzen des Urheberrechtes bed&uuml;rfen
    der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers.<br />

    <br />
    <strong>Haftungsausschluss:</strong> Die Inhalte dieser Website wurden mit
    gr&ouml;&szlig;tm&ouml;glicher Sorgfalt und nach bestem Wissen
    erstellt. Da Fehler jedoch nie auszuschlie&szlig;en sind und die Daten
    sowie weitere Inhalte Ver&auml;nderungen unterliegen k&ouml;nnen, weisen
    wir auf Folgendes hin: Wir &uuml;bernehmen keine Gew&auml;hr f&uuml;r die
    Aktualit&auml;t, Richtigkeit, Vollst&auml;ndigkeit oder Qualit&auml;t der
    auf dieser Website bereitgestellten Informationen. F&uuml;r Sch&auml;den
    materieller oder immaterieller Art, die durch die Nutzung oder
    Nichtnutzung der dargebotenen Informationen bzw. durch die Nutzung
    fehlerhafter und unvollst&auml;ndiger Informationen unmittelbar oder
    mittelbar verursacht werden, haften wir nicht, sofern nicht nachweislich
    vors&auml;tzliches oder grob fahrl&auml;ssiges Verschulden zur Last gelegt
    werden kann.<br />

    <br />
    <strong>Datenbasis:</strong> Es wurden die Anlagenstammdaten aus dem Jahr 2012, die
    unter der Ver&ouml;ffentlichungspflicht der Netzbetreiber nach &sect; 52
    EEG stehen von folgenden Anbietern verwendet:
    <ul style="margin-top: 12pt; margin-left: 30pt;" >
      <li> Mitnetz Leipzig: Stammdaten EEG-Jahresmeldung 2012 
(<a href="https://www.mitnetz-strom.de/irj/go/km/docs/z_ep_em_unt_documents/em/mitnetzstrom/Dokumente/Stammdaten_EEG-Jahresmeldung_2012_MITNETZ%20STROM.pdf">pdf</a>)</li>
      <li> EEG KWK: <a href="http://www.eeg-kwk.net/de/Anlagenstammdaten.htm"
    >Anlagenstammdaten</a> </li>
      <li> Netz Leipzig:
<a href="http://www.netz-leipzig.de/netzanschluesse/erzeugungsanlagen/?eID=dam_frontend_push&docID=358" 
    >Link</a></li>
      <li> 50Hertz: <a href="http://www.50hertz.com/cps/rde/xchg/trm_de/hs.xsl/165.htm">Link</a></li>
      <li> Die Karte wurde erstellt auf der Basis von <a href="http://leafletjs.com">Leaflet</a></li>
</ul>
</div>
<div class="clear"></div>
