<div class="textContent">
  <p>Willkommen auf der &bdquo;Erneuerbare Energien Map Leipzig&ldquo;</p>
  <br />
  <p>Hier finden Sie eine Karte mit allen dezentralen Energieerzeugungsanlagen
    in Leipzig.</p>  <br />
  <p>
    <b>Der Hintergrund</b><br /> &bdquo;Erneuerbare Energien sind der
    Schl&uuml;ssel zu einer nachhaltigen Energieversorgung&ldquo; - so wird es
    gesellschaftspolitisch diskutiert und praktiziert.  Das Gesetz zum Vorrang
    Erneuerbarer Energien (kurz EEG) formuliert die Wende von fossilen,
    ersch&ouml;pflichen zu sich regenerierenden, alternativen
    Energietr&auml;gern wie Solarstrahlung, Erdw&auml;rme und Windkraft.
    Dabei spielt nicht nur die Umsetzung dieses Vorhabens eine gro&szlig;e
    Rolle, sondern auch dessen Transparenz. Anlagenstammdaten zu erneuerbaren
    Energiequellen unterliegen laut &sect; 52 EEG der
    Ver&ouml;ffentlichungspflicht der Netzbetreiber (s. &bdquo;Gesetzliche
    Grundlage&ldquo;).
  </p>
  <br />
  <p>
    <b>Das Projekt</b><br /> Im Wintersemester 2013/2014 wurden von einem
    interdisziplin&auml;ren studentischen Projektteam am Institut f&uuml;r
    Informatik der Universit&auml;t Leipzig unter der Leitung von
    Prof. Dr. Hans-Gert Gr&auml;be die von den Netzbetreibern
    ver&ouml;ffentlichten Stammdaten entsprechender Anlagen aus der Region
    Leipzig gesammelt, f&uuml;r die Integration in
    die <a href="http://www.leipzig-data.de">Leipzig Data Datenbasis</a>
    aufbereitet und visualisiert.
  </p>
  <br />
  <p>
    <b>Die Idee</b><br /> Ziel des Projektes war es, sich nicht nur einen
    &Uuml;berblick &uuml;ber die Energiewende in Leipzig zu verschaffen und
    dies &ouml;ffentlich diskutierbar zu machen, sondern die Grundlage
    f&uuml;r eine Weiterf&uuml;hrung, Funktionserweiterung und Aktualisierung
    des Projekts zu legen. Nach Open Data Prinzipien auf der Basis des
    &bdquo;Linked Open Data&ldquo;-Konzeptes entworfen, bietet die e-Map
    Leipzig die M&ouml;glichkeit zur weiterf&uuml;hrenden Vernetzung von
    offenen Daten zur Energiewende in Leipzig und mit weiteren Informationen
    aus dem <a href="http://www.leipzig-data.de">Leipzig Data Projekt.</a>
  </p>
  <br />
  <p>
    <b>Begleitende Arbeiten</b><br /> Weitere Erfahrungen aus der Arbeit am
    Thema wurden in zwei Seminararbeiten aufgearbeitet:
    <ul style="margin: 10pt; margin-left: 30pt;">
      <li>Andreas Krause: Energiedaten im Internet.
	(<a href="Dokumente/Bericht_Energiedaten.pdf">pdf</a>)</li>
      <li>Ramon Bernert: Verfahren zur Solarstromprognose.
	(<a href="Dokumente/Bericht_Bernert.pdf">pdf</a>)</li>
      </ul>
  </p>
  <p>
    <b>Partizipation</b><br /> Die Daten sind in die (OntoWiki-basierte)
    <a href="http://www.leipzig-data.de/Data">Leipzig Data Datensammlung</a>
    integriert und k&ouml;nnen &uuml;ber
    den <a href="http://www.leipzig-data.de:8890/sparql">Leipzig Data SPARQL
    Endpunkt</a> frei durchsucht und geeignete Teile zur lokalen Verwendung
    heruntergeladen werden.  
    </p>
</div>
<div class="clear"></div>
