<div class="textContent">
  <div style="text-align: center"> 
    <h1> Rechtliche Lage - Ver&ouml;ffentlichungspflicht der
      Netzbetreiber </h1>
  </div> <br />
  <div style="text-align: justify">
    Das Gesetz f&uuml;r den Vorrang Erneuerbarer Energien, kurz Erneuerbare
    Energien Gesetz, regelt die bevorzugte Einspeisung von Strom aus
    erneuerbaren Quellen ins Stromnetz und garantiert deren Erzeugern feste
    Einspeiseverg&uuml;tungen und wurde urspr&uuml;nglich im M&auml;rz 2000
    verabschiedet (Wikipedia). F&uuml;r Netzbetreiber herrscht eine allgemeine
    Abnahmepflicht, wobei der Preis abh&auml;ngig von der
    Anlagengr&ouml;&szlig;e und dem Jahr der Inbetriebnahme ist. Bei
    Photovoltaikanlagen mit einer Nennleistung von bis zu 10kW betrug die
    Verg&uuml;tung im Januar 2014 13,68ct/kWh, wobei diese im Jahr 2001 noch
    bei 50,62 ct/kWh lag.  Das EEG reguliert und schreibt vor, welche
    Anlagendaten in welcher Form ver&ouml;ffentlich werden m&uuml;ssen. Diese
    relativ laxen Formulierungen lassen den Netz- und
    &Uuml;bertragungsnetzbetreibern jedoch einigen Spielraum in der
    Datenqualit&auml;t und Umfang der Ver&ouml;ffentlichungen. Anbei ein
    Auszug des EEG mit den wichtigsten Paragraphen die diese
    Ver&ouml;ffentlichungspflicht regeln sollen.  

    <div class="block">
      <b>&sect;46 EEG</b>: &bdquo;Anlagenbetreiberinnen und -betreiber sind
      verpflichtet, dem Netzbetreiber den Standort und die installierte
      Leistung der Anlage mitzuteilen [...]&ldquo; und bis zum 28. Februar
      eines Jahres die f&uuml;r die Endabrechnung des Vorjahres erforderlichen
      Daten zur Verf&uuml;gung zu stellen.
    </div> 

    &rarr; Die Betreiber einer Photovoltaikanlage teilen diese Daten in diesem
    Falle der Leipzig Netz GmbH mit, da dieser der lokale Netzbetreiber ist.
    
    <div class="block">
      <b>&sect;47 EEG</b>: Netzbetreiber [...] sind verpflichtet, ihrem
      vorgelagerten &Uuml;bertragungsnetzbetreiber die tats&auml;chlich
      geleisteten Verg&uuml;tungszahlungen nach &sect; 16, die Pr&auml;mien
      nach den &sect;&sect; 33g und 33i und die von den Anlagenbetreiberinnen
      und Anlagenbetreibern erhaltenen Meldungen zu &uuml;bermitteln.
    </div> 

    &rarr; Der Netzbetreiber Leipzig Netz GmbH muss also dem
    &Uuml;bertragungsnetzbetreiber, in unserem Fall der 50hertz GmbH, die
    zuvor akkumulierten Daten &uuml;bermitteln.

    <div class="block">
      <b>&sect;52 EEG</b>: Netzbetreiber und
      Elektrizit&auml;tsversorgungsunternehmen sind verpflichtet, auf ihren
      Internetseiten die Angaben nach den &sect;&sect; 45 bis 49
      unverz&uuml;glich nach ihrer &Uuml;bermittlung und [...] einen Bericht
      &uuml;ber die Ermittlung der von ihnen nach den &sect;&sect; 45 bis 49
      mitgeteilten Daten zu ver&ouml;ffentlichen.
    </div> 

    &rarr; Der Netzbetreiber Leipzig Netz GmbH muss zus&auml;tzlich zur
    &Uuml;bertragung diese Daten ebenfalls auf seinen eigenen Internetseiten
    ver&ouml;ffentlichen.  
 
    <div class="block">
      <b>(1a)</b> Die &Uuml;bertragungsnetzbetreiber sind verpflichtet die
      vermarkteten Strommengen [...] auf einer gemeinsamen Internetseite in
      nicht personenbezogener Form zu ver&ouml;ffentlichen.
    </div> 

    &rarr; Die zuvor von den Netzbetreibern an die
    &Uuml;bertragungsnetzbetreibern &uuml;bermittelten Daten m&uuml;ssen nun
    auf einer gemeinsamen Internetseite in nicht personenbezogener Form
    ver&ouml;ffentlich. Dieser Pflicht kommen die vier deutschen
    &Uuml;bertragungsnetzbetreiber 50hertz, amprion, Tennet und Transnet BW
    auf der Seite www.eeg-kwk.net nach.  <br /><br />
 
    <div class="block">
      <b>(2)</b> Die Angaben und der Bericht m&uuml;ssen eine sachkundige
    dritte Person in die Lage versetzen, ohne weitere Informationen die
    ausgeglichenen Energiemengen und Verg&uuml;tungszahlungen vollst&auml;ndig
    nachvollziehen zu k&ouml;nnen.
    </div> 

    &rarr; Zus&auml;tzlich m&uuml;ssen diese Daten die Anforderung
    erf&uuml;llen, eine dritte Person in die Lage zu versetzen, die
    Energiemengen und die Verg&uuml;tungszahlen nachvollziehen zu k&ouml;nnen.
    </div>

    <b>Quellen: </b> <br />
    <ul style="margin:1em 2em; line-height: 2em;">
        <li>
            <a href="http://de.wikipedia.org/wiki/Erneuerbare-Energien-Gesetz"
            >http://de.wikipedia.org/wiki/Erneuerbare-Energien-Gesetz</a>
        </li>
        <li>
            <a href="http://dejure.org/gesetze/EEG">Gesetzestext des EEG</a>
        </li>
        <li>
            <a href="http://www.eeg-kwk.net/">Gemeinsame Internetzseite der
            vier &Uuml;bertragungsnetzbetreiber</a>
        </li>
        <li>
            <a href="http://www.solarwirtschaft.de/fileadmin/media/pdf/eeg_verg_uebers.pdf"
            >Verg&uuml;tungssatze von Photovoltaik Anlagen ab 1. Juli 2012</a>
        </li>
        <li>
            <a href="http://www.netz-leipzig.de/netzanschluesse/erzeugungsanlagen/?eID=dam_frontend_push&docID=356"
            >Jahresbericht der Leipzig Netz GmbH nach &sect;52 EEG</a>
        </li>
    </ul>
</div>
<div class="clear"></div>
